config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                             Controller#Action
#     transaction_records GET    /transaction_records(.:format)          transaction_records#index
#                         POST   /transaction_records(.:format)          transaction_records#create
#  new_transaction_record GET    /transaction_records/new(.:format)      transaction_records#new
# edit_transaction_record GET    /transaction_records/:id/edit(.:format) transaction_records#edit
#      transaction_record GET    /transaction_records/:id(.:format)      transaction_records#show
#                         PATCH  /transaction_records/:id(.:format)      transaction_records#update
#                         PUT    /transaction_records/:id(.:format)      transaction_records#update
#                         DELETE /transaction_records/:id(.:format)      transaction_records#destroy
#                   banks GET    /banks(.:format)                        banks#index
#                         POST   /banks(.:format)                        banks#create
#                new_bank GET    /banks/new(.:format)                    banks#new
#               edit_bank GET    /banks/:id/edit(.:format)               banks#edit
#                    bank GET    /banks/:id(.:format)                    banks#show
#                         PATCH  /banks/:id(.:format)                    banks#update
#                         PUT    /banks/:id(.:format)                    banks#update
#                         DELETE /banks/:id(.:format)                    banks#destroy
#                   users GET    /users(.:format)                        users#index
#                         POST   /users(.:format)                        users#create
#                new_user GET    /users/new(.:format)                    users#new
#               edit_user GET    /users/:id/edit(.:format)               users#edit
#                    user GET    /users/:id(.:format)                    users#show
#                         PATCH  /users/:id(.:format)                    users#update
#                         PUT    /users/:id(.:format)                    users#update
#                         DELETE /users/:id(.:format)                    users#destroy

Rails.application.routes.draw do
  resources :conversations
  root :to => 'pages#home' # same as localhost 3000

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :transaction_records
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transaction_record.rb
class TransactionRecord < ApplicationRecord
  belongs_to :provider, class_name: 'User', :foreign_key => :provider_id
  belongs_to :reciver, class_name: 'User', :foreign_key => :reciver_id




  include Filterable

end

app/controllers/transaction_records_controller.rb
class TransactionRecordsController < ApplicationController
  before_action :set_transaction_record, only: [:show, :edit, :update, :destroy]

  # GET /transaction_records
  # GET /transaction_records.json
  def index
    @transaction_records = TransactionRecord.all
  end

  # GET /transaction_records/1
  # GET /transaction_records/1.json
  def show

  end

  # GET /transaction_records/new
  def new
    @transaction_record = TransactionRecord.new
    @transaction_record.reciver = @current_user
    @transaction_record.provider_id = $provider

  end

  # GET /transaction_records/1/edit
  def edit
  end

  # POST /transaction_records
  # POST /transaction_records.json
  def create
    @transaction_record = TransactionRecord.new(transaction_record_params)

    respond_to do |format|
      if @transaction_record.save
        format.html { redirect_to users_path, notice: 'Transaction record was successfully created.' }
        format.json { render :show, status: :created, location: @transaction_record }
      else
        format.html { render :new }
        format.json { render json: @transaction_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_records/1
  # PATCH/PUT /transaction_records/1.json
  def update
    respond_to do |format|
      if @transaction_record.update(transaction_record_params)
        format.html { redirect_to users_path, notice: 'Transaction record was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction_record }
      else
        format.html { render :edit }
        format.json { render json: @transaction_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_records/1
  # DELETE /transaction_records/1.json
  def destroy
    @transaction_record.destroy
    respond_to do |format|
      format.html { redirect_to transaction_records_url, notice: 'Transaction record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_record
      @transaction_record = TransactionRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_record_params
      params.require(:transaction_record).permit(:provider_id, :reciver_id, :credit, :review, :comments, :user)
    end
end

app/helpers/transaction_records_helper.rb
module TransactionRecordsHelper
end

app/views/transaction_records/_form.html.erb
<%# form_with(model: transaction_record, local: true) do |form| %>


<%= form_for transaction_record, :html => { :multipart => true } do |form| %>


  <% if transaction_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction_record.errors.count, "error") %> prohibited this transaction_record from being saved:</h2>

      <ul>
      <% transaction_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :provider %>
    <%= form.number_field :provider_id, id: :transaction_record_user_id %>
  </div>

  <div class="field">
    <%= form.label :reciver %>
    <%= form.number_field :reciver_id, id: :transaction_record_user_id %>
  </div>

  <div class="field">
    <%= form.label :credit %>
    <%= form.number_field :credit, min: 1, id: :transaction_record_credit %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.number_field :review, min: 1, max: 5, id: :transaction_record_review %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :transaction_record_comments %>
  </div>

  <div class="actions">
    <button><%= form.submit %></button>
  </div>
<% end %>

app/views/transaction_records/edit.html.erb
<h1>Editing Transaction Record</h1>

<%= render 'form', transaction_record: @transaction_record %>

<%= link_to 'Show', @transaction_record %> |
<%= link_to 'Back', transaction_records_path %>

app/views/transaction_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transaction Records</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>Reciver</th>
      <th>Credit</th>
      <th>Review</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_records.each do |transaction_record| %>
      <tr>

        <td><%= transaction_record.provider.name %></td>
        <td><%= transaction_record.reciver.name %></td>
        <td><%= transaction_record.credit %></td>
        <td><%= transaction_record.review %></td>
        <td><%= transaction_record.comments %></td>
        <td><%= link_to 'Show', transaction_record %></td>
        <td><%= link_to 'Edit', edit_transaction_record_path(transaction_record) %></td>
        <td><%= link_to 'Destroy', transaction_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_record_path %>

app/views/transaction_records/new.html.erb
<h1 <style="text-align:center" />Finish and comment your last deal</h1>

<%= render 'form', transaction_record: @transaction_record %>

<button class="back-buttom"><%= link_to 'Back', transaction_records_path %></button>

app/views/transaction_records/show.html.erb
<div class="new_transaction_record">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Provider:</strong>
    <%= @transaction_record.provider_id %>
  </p>

  <p>
    <strong>Reciver:</strong>
    <%= @transaction_record.reciver_id %>
  </p>

  <p>
    <strong>Credit:</strong>
    <%= @transaction_record.credit %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= @transaction_record.review %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= @transaction_record.comments %>
  </p>

  <%= link_to 'Edit', edit_transaction_record_path(@transaction_record) %> |
  <%= link_to 'Back', transaction_records_path %>
</div>