config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                             Controller#Action
#     transaction_records GET    /transaction_records(.:format)          transaction_records#index
#                         POST   /transaction_records(.:format)          transaction_records#create
#  new_transaction_record GET    /transaction_records/new(.:format)      transaction_records#new
# edit_transaction_record GET    /transaction_records/:id/edit(.:format) transaction_records#edit
#      transaction_record GET    /transaction_records/:id(.:format)      transaction_records#show
#                         PATCH  /transaction_records/:id(.:format)      transaction_records#update
#                         PUT    /transaction_records/:id(.:format)      transaction_records#update
#                         DELETE /transaction_records/:id(.:format)      transaction_records#destroy
#                   banks GET    /banks(.:format)                        banks#index
#                         POST   /banks(.:format)                        banks#create
#                new_bank GET    /banks/new(.:format)                    banks#new
#               edit_bank GET    /banks/:id/edit(.:format)               banks#edit
#                    bank GET    /banks/:id(.:format)                    banks#show
#                         PATCH  /banks/:id(.:format)                    banks#update
#                         PUT    /banks/:id(.:format)                    banks#update
#                         DELETE /banks/:id(.:format)                    banks#destroy
#                   users GET    /users(.:format)                        users#index
#                         POST   /users(.:format)                        users#create
#                new_user GET    /users/new(.:format)                    users#new
#               edit_user GET    /users/:id/edit(.:format)               users#edit
#                    user GET    /users/:id(.:format)                    users#show
#                         PATCH  /users/:id(.:format)                    users#update
#                         PUT    /users/:id(.:format)                    users#update
#                         DELETE /users/:id(.:format)                    users#destroy

Rails.application.routes.draw do
  resources :conversations
  root :to => 'pages#home' # same as localhost 3000

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :transaction_records
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User', :foreign_key => :sender_id
  belongs_to :helper, class_name: 'User', :foreign_key => :helper_id

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
    @conversation.sender = @current_user
    @conversation.helper_id = $helper
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to users_path, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:sender_id, :helper_id, :comments, :user)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%# form_with(model: conversation, local: true) do |form| %>

<%= form_for conversation, :html => { :multipart => true } do |form| %>

  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="new_transaction_record">
  <div class="field">
    <%= form.label :sender %>
    <%= form.text_field :sender_id, id: :user_name %>
  </div>


  <div class="field">
    <%= form.label :helper %>
    <%= form.number_field :helper_id, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conversations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.sender.name %></td>
        <td><%= conversation.helper.name %></td>
        <td><%= conversation.comments %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<button class="back-buttom"><%= link_to 'Back', conversations_path %></button>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<button class="back-buttom"><%= link_to 'Back', conversations_path %></button>