config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                             Controller#Action
#     transaction_records GET    /transaction_records(.:format)          transaction_records#index
#                         POST   /transaction_records(.:format)          transaction_records#create
#  new_transaction_record GET    /transaction_records/new(.:format)      transaction_records#new
# edit_transaction_record GET    /transaction_records/:id/edit(.:format) transaction_records#edit
#      transaction_record GET    /transaction_records/:id(.:format)      transaction_records#show
#                         PATCH  /transaction_records/:id(.:format)      transaction_records#update
#                         PUT    /transaction_records/:id(.:format)      transaction_records#update
#                         DELETE /transaction_records/:id(.:format)      transaction_records#destroy
#                   banks GET    /banks(.:format)                        banks#index
#                         POST   /banks(.:format)                        banks#create
#                new_bank GET    /banks/new(.:format)                    banks#new
#               edit_bank GET    /banks/:id/edit(.:format)               banks#edit
#                    bank GET    /banks/:id(.:format)                    banks#show
#                         PATCH  /banks/:id(.:format)                    banks#update
#                         PUT    /banks/:id(.:format)                    banks#update
#                         DELETE /banks/:id(.:format)                    banks#destroy
#                   users GET    /users(.:format)                        users#index
#                         POST   /users(.:format)                        users#create
#                new_user GET    /users/new(.:format)                    users#new
#               edit_user GET    /users/:id/edit(.:format)               users#edit
#                    user GET    /users/:id(.:format)                    users#show
#                         PATCH  /users/:id(.:format)                    users#update
#                         PUT    /users/:id(.:format)                    users#update
#                         DELETE /users/:id(.:format)                    users#destroy

Rails.application.routes.draw do
  resources :conversations
  root :to => 'pages#home' # same as localhost 3000

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :transaction_records
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :recivers, :class_name => 'TransactionRecord', :foreign_key => 'reciver_id'
  has_many :providers, :class_name => 'TransactionRecord', :foreign_key => 'provider_id'
  has_many :senders, :class_name => 'Conversation', :foreign_key => 'sender_id'
  has_many :helpers, :class_name => 'Conversation', :foreign_key => 'helper_id'

  validates :email, :presence => true, :uniqueness => true

  geocoded_by :address   #using geocoder to convert location into coordinates
  after_validation :geocode   # auto-fetch coordinates

  mount_uploader :image, ImageUploader, :presence => false, :optional => true

  include Filterable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    $helper = @user.id
    $provider = $helper

    @transaction_record = TransactionRecord.all

    @conversation = Conversation.all
    # raise hell
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_later

        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user

      @user = User.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password_digest, :address, :skill, :image, :password, :longitude, :latitude)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="new_transaction_record">

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>

  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :user_address %>
  </div>

  <div class="field">
    <%= form.label :skill %>
    <%= form.text_area :skill, id: :user_skill %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :user_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Address</th>
      <th>Skill</th>
      <th>Image</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.address %></td>
        <td><%= user.skill %></td>

        <td><%= user.image %></td>
        <td><%= user.longitude %></td>
        <td><%= user.latitude %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->


  <div class="container latest">
    <div class="row">
      <div class="col-xs-12 ">
        <h1>Users Profiles</h1>
      </div>
      <% @users.each do |user| %>
        <a href="<%= users_path %>"> <%# 3 ways product || product_path product.id %>
          <div class="col-xs-12 col-md-4 wrap-users wrap">
            <figure>
              <% if user.image.present? %>
                <img src="<%=user.image%>" class="img-profile img-rounded" />
                <%# To get the image I created a method in product.rb in the model so we can use everywhere in products view, contorller and model  %>
              <% else %>
                <img class="img-profile img-responsive" src="https://museum.wales/media/40374/thumb_480/empty-profile-grey.jpg" alt="" />
              <% end %>
            </figure>
            <div class="wrap-text">
              <h3><%= link_to user.name, user %></h3>
              <%= user.skill %><br>
            </div><!-- end text-container -->
          </div><!-- end wrap-products -->
        </a><!-- end link -->
      <% end %>
    </div><!-- end row -->
  </div><!-- end container -->

<!-- <%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<button class="back-buttom"><%= link_to 'Back', users_path %></button>

app/views/users/show.html.erb
<div class="container latest">
  <div class="row">
    <div class="col-md-7">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @user.address %>
    </p>

    <p>
      <strong>Skills:</strong>
      <%= @user.skill %>
    </p>
    <p><Strong>Credits:</strong> <%= @user.providers.sum(:credit).round %></p>
  </div>

    <p>
      <strong>Image:</strong>
      <br>
      <% if @user.image.present? %>
        <%= image_tag @user.image.thumb.url %>
      <% else %>
        <%= image_tag('avatar-default.png') %>
      <% end %>
    </p>


    <!-- Geolocation -->
  <div class="col-md-6">
      <div class="maps">
        <img ><%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@user.latitude}%2C#{@user.longitude}" %></img>
      </div>
  </div>


      <!-- Send Message buttom -->
      <div class="buttoms">
        <% if @current_user.present? %>
        <div class="buttoms">
        <button><%= link_to 'Send Message', new_conversation_path %></button><br>
        </div>
        <div class="buttoms">
        <button><%= link_to 'Finish and comment your last deal',new_transaction_record_path %></button><br>
        <% end %>

      </div>
        <div class="buttoms">
        <!-- Back buttom -->
        <button> <%= link_to 'Back', users_path %></buttom>
      </div>
  </div>

  <!-- RATING  Stars -->
  <div class="rating">
    <h3>Rating of <%= @user.name %> </h3>
    <% if @user.providers.present? %>
      <% @user.providers.average(:review).round.times do %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
    <% end %>
  </div>


<!-- History -->
  <div class="record">
      <h3>History</h3>
      <div class="provider">
      <h4><%= @user.name %> as a provider</h4>
        <br>
        <table class="table table-striped">
          <thead>
            <tr>

              <th>Provider</th>
              <th>Reciver</th>
              <th>Review</th>
              <th>Credit</th>
            </tr>
          </thead>

          <tbody>
            <% @transaction_record.each do |transaction_record| %>
          <% if transaction_record.provider == @user  %>
            <tr>
              <td><%= transaction_record.provider.name %></td>
              <td><%= transaction_record.reciver.name %></td>
              <td><%= transaction_record.review %></td>
              <td><%= transaction_record.credit %></td>

            </tr>
          <% end %>
        <% end %>
          </tbody>
        </table>


      </div>

    <div class="reciver-table">
    <h4>Reviews as a receiver</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Provider</th>
            <th>Reciver</th>
            <th>Review</th>
            <th>Credit</th>
          </tr>
        </thead>

        <tbody>
          <% @transaction_record.each do |transaction_record| %>
        <% if  transaction_record.reciver == @user %>
          <tr>
            <td><%= transaction_record.provider.name %></td>
            <td><%= transaction_record.reciver.name %></td>
            <td><%= transaction_record.review %></td>
            <td><%= transaction_record.credit %></td>

          </tr>
        <% end %>
      <% end %>
        </tbody>
      </table>
    </div>
  </div>

<div class="comments">
  <div class="comments-sender">
    <h4>Sent messages</h4>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Sender</th><br>
          <th>Helper</th>
          <th>Messages</th>
        </tr>
      </thead>
      <tbody>
        <% @conversation.each do |conversation| %>
        <% if conversation.sender_id == @user.id %>
          <tr>
            <td><%= conversation.sender.name %></td>
            <td><%= conversation.helper.name %></td>
            <td><%= conversation.comments %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
    <div class="coments-helper">
      <h4>Recived messages</h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Sender</th><br>
            <th>Helper</th>
            <th>Messages</th>
          </tr>
        </thead>
        <tbody>
          <% @conversation.each do |conversation| %>
          <% if conversation.helper_id == @user.id %>
            <tr>
              <td><%= conversation.sender.name %></td>
              <td><%= conversation.helper.name %></td>
              <td><%= conversation.comments %></td>
            </tr>
            <% end %>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>

</div>

</div>

<!-- sdfs -->