config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                             Controller#Action
#     transaction_records GET    /transaction_records(.:format)          transaction_records#index
#                         POST   /transaction_records(.:format)          transaction_records#create
#  new_transaction_record GET    /transaction_records/new(.:format)      transaction_records#new
# edit_transaction_record GET    /transaction_records/:id/edit(.:format) transaction_records#edit
#      transaction_record GET    /transaction_records/:id(.:format)      transaction_records#show
#                         PATCH  /transaction_records/:id(.:format)      transaction_records#update
#                         PUT    /transaction_records/:id(.:format)      transaction_records#update
#                         DELETE /transaction_records/:id(.:format)      transaction_records#destroy
#                   banks GET    /banks(.:format)                        banks#index
#                         POST   /banks(.:format)                        banks#create
#                new_bank GET    /banks/new(.:format)                    banks#new
#               edit_bank GET    /banks/:id/edit(.:format)               banks#edit
#                    bank GET    /banks/:id(.:format)                    banks#show
#                         PATCH  /banks/:id(.:format)                    banks#update
#                         PUT    /banks/:id(.:format)                    banks#update
#                         DELETE /banks/:id(.:format)                    banks#destroy
#                   users GET    /users(.:format)                        users#index
#                         POST   /users(.:format)                        users#create
#                new_user GET    /users/new(.:format)                    users#new
#               edit_user GET    /users/:id/edit(.:format)               users#edit
#                    user GET    /users/:id(.:format)                    users#show
#                         PATCH  /users/:id(.:format)                    users#update
#                         PUT    /users/:id(.:format)                    users#update
#                         DELETE /users/:id(.:format)                    users#destroy

Rails.application.routes.draw do
  resources :conversations
  root :to => 'pages#home' # same as localhost 3000

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :transaction_records
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankOfTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="nav">
      <nav>
        <div class="main_nav">
          <ul>
            <li style="color:lightblue"><%= link_to 'Home', root_path %></li>

            <% if @current_user.present?%>
            <li style="color:lightblue"><%= link_to "#{ @current_user.name }'s profile",  @current_user %></li>
            <% else %></li>
            <!-- <li style="color:lightblue"><%= link_to 'Transaction Record', users_path %></li> -->
            <% end %>
            <li style="color:lightblue"><%= link_to 'Profiles', users_path %></li>
          </ul>
        </div>
        <div class="signup_nav">
          <ul>
          <li>
            <% if @current_user.present?%>
              <%= link_to "Sign out #{ @current_user.email }", login_path, :method => 'delete', :class => 'small-signin' %>
            <% else %></li>
            <li><%= link_to 'Sign up', new_user_path %><%= link_to 'Log in', login_path %></li>
            <!-- <li><%= link_to 'Log in', login_path %></li> -->
          </ul>
          <% end %>
        </div>
      </nav>
    </header>



    <div>
        <%= yield %>
    </div>


    <footer class="footer-distributed">

      <div class="footer-left">

        <h3>Bank Of Time</h3>

        <p class="footer-links">
          <%= link_to 'Home', root_path %>
          |
          <%= link_to 'Profiles', users_path %>

        </p>

        <p class="footer-company-name">Bank of Time &copy; 2018</p>
      </div>

      <div class="footer-center">

        <div>
          <i class="fa fa-map-marker"></i>
          <p><span>21 Revolution Street</span> Sydney, Australia</p>
        </div>

        <div>
          <i class="fa fa-phone"></i>
          <p>+61 455 123456</p>
        </div>

        <div>
          <i class="fa fa-envelope"></i>
          <p><a href="bankoftime@company.com">support@bankoftime.com</a></p>
        </div>

      </div>

      <div class="footer-right">

        <p class="footer-company-about">
          <span>About the company</span>
          It is a system of exchange of services for services or favors for favors.
          It offers the advantage of fostering social relations and equality between
           different economic strata</p>

        <div class="footer-icons">

          <a href="#"><i class="fa fa-facebook">Facebook</i></a><br>
          <a href="#"><i class="fa fa-twitter">Twiter</i></a>

        </div>

      </div>

    </footer>
  </body>
</html>